### ISSUE TITLE
Failed to preset unit

### ISSUE THREAD

**Issue by saikek** [mcuadros/OctoPrint-TFT#11]
Hello All.
I've tried different distributions - OctoPi 0.14+ WaveShare 3.2inch scripts, WaveShare image for 3.2 inch screen with updates to Debian Stretch, but i'm getting issues installing service.

On the post-install script error occurs:
```
Failed to preset unit: File /etc/systemd/system/display-manager.service already exists and is a symlink to /lib/systemd/system/lightdm.service.
/usr/bin/deb-systemd-helper: error: systemctl preset failed on octoprint-tft.service: No such file or directory
```

Service `octoprint-tft` is installed & running.
I've tried removing `/etc/systemd/system/display-manager.service`, but it does not helps.

What would be the correct way to start the UI from console (for testing purposes)? 
`startx` just prints warnings into console, 
`raspi-config` and choosing to boot into UI does not help as well.

**Comment by mcuadros** [comment]
Weird, should work. Can you remove the lightdm package and reinstall?

**Comment by saikek** [comment]
Closing the issue, not relevan anymore.
