### ISSUE TITLE
Can't connect to Octoprint

### ISSUE THREAD

**Issue by peteboz** [mcuadros/OctoPrint-TFT#16]
I have a 2.8" Adafruit TFT connected to a raspberry pi 3 and the octoprint logo shows on the screen, but nothing else happens.  I don't see any icons or text except for the background.

I can confirm the octoprint server is up, I can reach it by web browser, and I can wget it also locally using localhost:5000.  I've placed the hostname, API key in the config.  Any ideas and anything I can do to debug further?

Thanks in advance!

**Comment by CJeffyB** [comment]
Is the printer actually powered on, and connected to the OctoPrint server?  When OctoPrint-TFT can't connect to the printer, it shows the logo on screen, with nothing else.  Once I bring my server up, everything works fine.
You can also see if the TFT is constantly trying to connect to the printer, by checking out the Terminal tab of OctoPrint in the web interface.  (Referenced in this bug: [https://github.com/mcuadros/OctoPrint-TFT/issues/15](https://github.com/mcuadros/OctoPrint-TFT/issues/15))

**Comment by peteboz** [comment]
Thank you for the fast reply.  That was the issue - I didn't have my printer on!  I was trying to get it all setup before connecting the printer to it and I had assumed that since the octoprint server was running that it would work.  Now it makes sense.  Thanks again!
