### ISSUE TITLE
calibration issue

### ISSUE THREAD

**Issue by peteboz** [mcuadros/OctoPrint-TFT#17]
I'm using an 2.8" Adafruit TFT with a raspberry pi 3 and it seems like the touch presses are way off, enough so most buttons are impossible to press.  As far as setup, I've installed the adafruit drivers per these instructions:
https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/easy-install

I've even ran the manual calibration setup and confirmed the accuracy crosshairs using the utility here:
https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/resistive-touchscreen-manual-install-calibrate

I'm wondering if OctoPrint-TFT is using a different set of calibration parameters than what the adafruit scripts have?

Thanks in advance.

**Comment by mcuadros** [comment]
It doesn't use any special setting for the calibration. OctoPrint-TFT is an X application running on your Xorg server. If a windows manager works this should work.

**Comment by TheNore** [comment]
this is also happening to me. tried search everywhere but kept coming back to here. is there any solution? I have followed 5 walk throughs and this is the only one i got to boot my device, but i keep running into this touch calibration issue making the platform unusable. https://github.com/mcuadros/OctoPrint-TFT/issues/13

**Comment by TheNore** [comment]
found the fix in a previous calibration issue post. I use fbdev for my touch driver and entered the code below to fix it. I am also running the jessie image on stretch bc I couldn't get the 1.2-1 stretch image  to boot.

I update the file /usr/share/X11/xorg.conf.d/40-libinput.conf

I added Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1" in InputClass section dedicated to touchscreens

```
Section "InputClass"
        Identifier "fbdev touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "fbdev"
        Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1"
EndSection
```
