### ISSUE TITLE
support for 7inch tft

### ISSUE THREAD

**Issue by amrithmmh** [mcuadros/OctoPrint-TFT#19]
is there a support for 7inch screen ?

thanks for the great application

**Comment by herrwusel** [comment]
You can configure the resolution in Octoprint-TFT so a 7" touch display should work.

**Comment by amrithmmh** [comment]
@herrwusel thanks for the reply

**Comment by mcuadros** [comment]
Exactly this. You must provide the correct resolution for your screen.
