### ISSUE TITLE
ability to theme or change interface?

### ISSUE THREAD

**Issue by amrithmmh** [mcuadros/OctoPrint-TFT#20]
how do i edit the software source to change the interface ?
is there a way to change the appearence without modifying the source code?

**Comment by amrithmmh** [comment]
OCTOPRINT_TFT_STYLE_PATH=/opt/octoprint-tft/styles/default/
how to add themes?

**Comment by amrithmmh** [comment]
https://github.com/mcuadros/OctoPrint-TFT/tree/master/styles/default 
saw this css file and images. Is there a directory used by Octoprint-TFT(i think this awesome application needs a really good name)?

**Comment by mrcg** [comment]
I am searching for the same information.
As you have closed this entry ... can you share how to change the theme?
Thanks

**Comment by amrithmmh** [comment]
@mrcg just follow the link i posted before
the path after installing octoprint tft  /opt/octoprint-tft/styles/default/ is the path you place style.css file and images in a folder 
use this https://github.com/mcuadros/OctoPrint-TFT/tree/master/styles/default

**Comment by amrithmmh** [comment]
const (
	ImageFolder = "images"
	CSSFilename = "style.css"
)
@mrcg  just check for these two files in your installation

**Comment by mrcg** [comment]
Thanks for your reply.
Anyhow i have no clue which values to adjust in style.css in order to achieve theme like in the screenshot. 
It would be great to have some styles files preconfigured. Not only that it's easier but also to understand how it works.
Thx
