### ISSUE TITLE
Disable screen timeout

### ISSUE THREAD

**Issue by mstofflett** [mcuadros/OctoPrint-TFT#24]
Any idea how to disable screen timeout on a 3.5 RPi Touch Screen? Tried almost everything under the sun with no luck

**Comment by mstofflett** [comment]
Thats it, thanks!

**Comment by mrcg** [comment]
I do not find this file: sudo nano /etc/kbd/config
I have also searched for all "config" files but none contained similar information.
Where can i find the right file to be edited?

Thanks
