### ISSUE TITLE
Can't connect to OctoPi server

### ISSUE THREAD

**Issue by zekeadam** [mcuadros/OctoPrint-TFT#27]
I'm using the latest version of OctoPi, followed every instruction, tried every configuration like pointing to the config file or using the HTTP address and API key instead but no luck. It hangs on the connecting to OctoPrint Server screen.

**Comment by CJeffyB** [comment]
Any chance this is related to the following issue:
https://github.com/mcuadros/OctoPrint-TFT/issues/15
??

**Comment by zekeadam** [comment]
Thanks for pointing this out, I must have been overlooked this when I was reading through the issues. 

I also had to remove a bad X conf file as mentioned in #13 
And had the same size issue as #8 on my 800x480 screen.

By the way great project, this is the only reason why I bought a screen.
