### ISSUE TITLE
Error during file refresh from SD and local

### ISSUE THREAD

**Issue by zen** [mcuadros/OctoPrint-TFT#3]
Hi
First of all - thank you for the excellent software. I really hate TouchUI on 3.5 interface, it's not usable at all. I started using OctoPrint-TFT and I'm really happy so far, with some exceptions. I captured couple of bugs and this is the new one.
When updating list of files I'm getting following error
![img_20180103_172440](https://user-images.githubusercontent.com/25633/34543608-031f5238-f0e2-11e7-8d5c-c882e1c6236f.jpg)

Because I cannot refresh files I'm unable to print anything that was uploaded after OctoPrint-TFT service started. This affects both SD files and local octopi files.

**Comment by mcuadros** [comment]
Ouch, I am so used to work on system where int == int64, than I forgot that sometime can be int32, I am going to fix this at https://github.com/mcuadros/go-octoprint, and issue a new version this afternoon. Thanks for trying it!.

BTW this message being not center is another bug :(

**Comment by mcuadros** [comment]
I must ot say that I even tried my self, I am working 3d printer, I am finishing my HyperCube, so ... happy to have another beta tester.

**Comment by mcuadros** [comment]
https://github.com/mcuadros/go-octoprint/commit/01362f94e21fd2fd43e430358b250cfa89eeab44

**Comment by zen** [comment]
I also just built HEVO, but this instance in now connected to my more stable (for now) Prusa clone. I will compile it and test tomorrow. Thanks for the fix!

**Comment by zen** [comment]
Package built, available here: http://repo.napierala.org/deb/ if someone has time tonight.

**Comment by zen** [comment]
@mcuadros Looks like the script is always building for amd arch. I'm on Mac OSX, how can I cross compile for armhf? I changed "PKG_ARCH = armhf" but it didn't help

**Comment by mcuadros** [comment]
Go with cgo, is extremely hard to cross compile, I am using a remote docker at a RPi3

**Comment by zen** [comment]
I'll try on RPI3 then

**Comment by mcuadros** [comment]
I am building the packages right now

**Comment by mcuadros** [comment]
https://github.com/mcuadros/OctoPrint-TFT/releases/tag/v0.1.1

**Comment by zen** [comment]
I already built them, confirmed: working now, but I will need to fill couple of new bugs ;)
