### ISSUE TITLE
Stuck on "Connecting to Octoprint ...."

### ISSUE THREAD

**Issue by mrcg** [mcuadros/OctoPrint-TFT#32]
I have installed OctoPrint-TFT following all the details from #3.
Waveshare 3.5" display is installed and working.
Octoprint is up and running ... can also connect via browser from other PC.
Unforunately OctoPrint-TFT is getting stuck with Octoprint Logo and says "Connecting to Octoprint ...".

octoprint-tft-environment
OCTOPRINT_HOST=http://localhost     ====> also tried: http:127.0.0.1 and http://octopi.local
OCTOPRINT_API=*my-api*  
OCTOPRINT_CONFIG_FILE=/home/pi/.octoprint/config.yaml
OCTOPRINT_TFT_SYTLE_PATH=/opt/octoprint-tft/styles/default/
OCTOPRINT_TFT_RESOLUTION=

octoprint-tft.services
ExecStart=/usr/bin/xinit /usr/bin/OctoPrint-TFT -- :1 -nolisten tcp -nocursor

Any idea who to solve the issue?

![octoprint-tft_01](https://user-images.githubusercontent.com/4404991/41206150-f16e7de4-6cff-11e8-8229-dd4f78f0a45a.jpg)

**Comment by mrcg** [comment]
Meanwhile i have learned that OctoPrint-TFT requires 3d printer in CONNECTED mode.
Otherwise it's not booting up as shown in my screenshot.

You should definetely mention this in the initial instruction or (even better) mention this on the LCD screen. "Connecting to OctoPrint..." or "Waiting for connection to printer ..." would be self explaining. Beside this i would prefer to get "Connect to printer" button.

Do not consider this as a blame but even more as constructive feedback which will further improve the user experience with OctoPrint-TFT.

Finally i need to mention that OctoPrint-TFT is AMAZING !!!
It's pretty nice and the best OctoPrint UI for small size LCD screen.
For easier installation it would be great to have this as plugin version ... if possible???

**Comment by amrithmmh** [comment]
your lcd screen driver shows inverted colors ...please do try to install the correct driver

**Comment by amrithmmh** [comment]
use this @mrcg  https://github.com/goodtft/LCD-show

**Comment by RClabTV** [comment]
> Meanwhile i have learned that OctoPrint-TFT requires 3d printer in CONNECTED mode.
> Otherwise it's not booting up as shown in my screenshot.
> 
> You should definetely mention this in the initial instruction or (even better) mention this on the LCD screen. "Connecting to OctoPrint..." or "Waiting for connection to printer ..." would be self explaining. Beside this i would prefer to get "Connect to printer" button.
> 

I was setting up my Pi at my desk and had the same problem. Would really be nice if you would just change "Connecting to Octoprint" to "Connecting to Printer" or something like this.

Thank you for this project, I really like it, great UI for the 3.5" TFT
