### ISSUE TITLE
Question only: style.css config same as screenshot

### ISSUE THREAD

**Issue by mrcg** [mcuadros/OctoPrint-TFT#33]
How to configure the style.css in order to have the same nice look like this screenshot?
Can someone post the settings for this?

https://user-images.githubusercontent.com/1573114/33559609-a73a969e-d90d-11e7-9cf2-cf212412aaa5.png

Also other nice sytle's appreciated.
Thx
Christian

**Comment by amrithmmh** [comment]
the screenshot is the default gui

**Comment by mrcg** [comment]
It looks not that dark grey on my LCD.
Which value do i need to change if i want to change the background to e.g. black and the font to e.g. white?
THANKS

**Comment by amrithmmh** [comment]
I guess i have already answered your question...the driver you installed is not proper for waveshare tft(i had the same experience :-) )

**Comment by mrcg** [comment]
MANY THANKS FOR THE TIP !!!!
After installing the LCDSHOW driver the colors are correct.
Now i love octoprint-tft even more.

It's the best Octoprint UI for LCD screens.
Would be really great to see further development e.g. support some predefine themes for selection.
