### ISSUE TITLE
(solved) Buttons partially out of screen

### ISSUE THREAD

**Issue by daveliberato** [mcuadros/OctoPrint-TFT#44]
I'm using the Adafruit 800x480 LCD and i can't get the screen scaled properly. 

I've set the resolution in all the places, but there's still about 10/15 pixels out of screen on the right and bottom sides. Increasing the font size makes it worse. 

Is there any relation between the screen resolution, button height/width, and font size?
What am I missing?

Thanks

**Comment by tape2005** [comment]
![sphotoeditor-20181114_123250](https://user-images.githubusercontent.com/30298379/48482953-04a46600-e80a-11e8-95dc-5cf9db5e7153.jpg)

**Comment by daveliberato** [comment]
@tape2005 has found the problem. If the splash image is the same size as the resolution, the margins force the ui out of the screen. Reducing the image size fixed the problem ;)
