### ISSUE TITLE
Scaling issue on 7" 800x480 screen

### ISSUE THREAD

**Issue by TheBekker** [mcuadros/OctoPrint-TFT#48]
Using an offcial raspberry pi 7" screen with a resolution of 800x480.
Config set as: OCTOPRINT_TFT_RESOLUTION=800x480

Results in the bottom row of button being outside of screen.

[https://lh3.googleusercontent.com/rSUnnZcqrpYCFXt4j996aR9lE__d1Ar1uWST-hU4lFXLUuyJQqVVdVc4Z0Vl_aSpe5WYjvSEPG5lduYHVmMm267aXtcx59uE5Sm6E23f8XWN7C-bTIvTYsmW38TOVz8KJwtNVdlNLA=w1744-h1308-no](url)

**Comment by ururk** [comment]
Unfortunately, this is a known issue:

https://github.com/mcuadros/OctoPrint-TFT/issues/26

You will have to build the repository to get an installation package. However... I went ahead and did this and on one Raspberry Pi it now freezes after a print starts - the other one stays responsive. I "lived" with 480x480 for a long time... it works but is annoying.

**Comment by tonylam07** [comment]
So which I try to change 
`sudo nano /etc/octoprint-tft-environment
OCTOPRINT_TFT_RESOLUTION=800x480`
the loading screen is fine however the ui screen shows the bottom as being cut off.

**Comment by TheBekker** [comment]
After some research i would not recommend using this original project, it seem to be unmaintained, and a lot of stuff doesn't work. 
Also bugs like the mentioned freeze.

**Comment by littleferris** [comment]
@TheBekker which branch would you recommend then?
