### ISSUE TITLE
installation problem on 3.5inch RPi Display(MPI3501)

### ISSUE THREAD

**Issue by serv16** [mcuadros/OctoPrint-TFT#52]
Hello,

I am a beginner and french (excuse me for my english).

I bought this 3.5inch RPi Display(MPI3501), I install the driver [https://github.com/goodtft/LCD-show], followed the installation ocotopi-lcd, but I can't display OCTOPI-LCD.
The screen works, I have the OCTOPI login page.
![1](https://user-images.githubusercontent.com/32510358/52691118-1d82fb80-2f60-11e9-828e-189d07c2dc3e.jpg)

I don't know what to put in the file X config file, nor how to name it.

Can you help me please?

**Comment by nad22** [comment]
Same Problem here with 2 different Installations,...

**Comment by serv16** [comment]
I executed `systemctl status display-manager`, below the result :

> ● octoprint-tft.service - OctoPrint-TFT
   Loaded: loaded (/lib/systemd/system/octoprint-tft.service; enabled; vendor preset: enable
   Active: active (running) since Wed 2019-02-13 17:48:22 UTC; 13s ago
 Main PID: 1348 (xinit)
      CPU: 76ms
   CGroup: /system.slice/octoprint-tft.service
           └─1348 /usr/bin/xinit /usr/bin/OctoPrint-TFT -- :1 -nolisten tcp -nocursor
Feb 13 17:48:22 octopi xinit[1348]: (EE)
Feb 13 17:48:22 octopi xinit[1348]: Fatal server error:
Feb 13 17:48:22 octopi xinit[1348]: (EE) no screens found(EE)
Feb 13 17:48:22 octopi xinit[1348]: (EE)
Feb 13 17:48:22 octopi xinit[1348]: Please consult the The X.Org Foundation support
Feb 13 17:48:22 octopi xinit[1348]:          at http://wiki.x.org
Feb 13 17:48:22 octopi xinit[1348]:  for help.
Feb 13 17:48:22 octopi xinit[1348]: (EE) Please also check the log file at "/var/log/Xorg.1.
Feb 13 17:48:22 octopi xinit[1348]: (EE)
Feb 13 17:48:22 octopi xinit[1348]: (EE) Server terminated with error (1). Closing log file.
~
~
~
~
~
lines 1-18/18 (END)

**Comment by serv16** [comment]
Below the log file at "/var/log/Xorg.1.log" :

> [2732.522]
X.Org X Server 1.19.2
Release Date: 2017-03-02
[  2732.522] X Protocol Version 11, Revision 0
[  2732.522] Build Operating System: Linux 4.9.41-v7+ armv7l Raspbian
[  2732.523] Current Operating System: Linux octopi 4.14.97-v7+ #1197 SMP Mon Feb 4 21:13:29 GMT 2019 armv7l
[  2732.523] Kernel command line: 8250.nr_uarts=1 bcm2708_fb.fbwidth=640 bcm2708_fb.fbheight=480 bcm2708_fb.fbswa$
[  2732.523] Build Date: 18 October 2017  04:55:30PM
[  2732.523] xorg-server 2:1.19.2-1+rpt1+deb9u2 (https://www.debian.org/support)
[  2732.523] Current version of pixman: 0.34.0
[  2732.523]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[  2732.523] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  2732.524] (==) Log file: "/var/log/Xorg.1.log", Time: Wed Feb 13 18:04:37 2019
[  2732.524] (==) Using config directory: "/etc/X11/xorg.conf.d"
[  2732.525] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  2732.527] (==) No Layout section.  Using the first Screen section.
[  2732.527] (==) No screen section available. Using defaults.
[  2732.527] (**) |-->Screen "Default Screen Section" (0)
[  2732.527] (**) |   |-->Monitor "<default monitor>"
[  2732.528] (==) No device specified for screen "Default Screen Section".
        Using the first device section listed.
[  2732.528] (**) |   |-->Device "Allwinner A10/A13/A20 FBDEV"
[  2732.529] (**) |   |-->GPUDevice "tft35a"
[  2732.529] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[  2732.529] (==) Automatically adding devices
[  2732.529] (==) Automatically enabling devices
[  2732.529] (==) Automatically adding GPU devices
[  2732.529] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  2732.529] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  2732.529]    Entry deleted from font path.
[  2732.529] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  2732.529]    Entry deleted from font path.
[  2732.529] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  2732.529]    Entry deleted from font path.
[  2732.529] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  2732.529]    Entry deleted from font path.
[  2732.529] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  2732.529]    Entry deleted from font path.
[  2732.530] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  2732.530]    Entry deleted from font path.
[  2732.530] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        built-ins
[  2732.530] (==) ModulePath set to "/usr/lib/xorg/modules"
[  2732.530] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[  2732.530] (II) Loader magic: 0x1fbf40
[  2732.530] (II) Module ABI versions:
[  2732.530]    X.Org ANSI C Emulation: 0.4
[  2732.530]    X.Org Video Driver: 23.0
[  2732.530]    X.Org XInput driver : 24.1
[  2732.530]    X.Org Server Extension : 10.0
[  2732.534] (--) using VT number 2
[  2732.534] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[  2732.535] (II) no primary bus or device found
[  2732.535] (II) LoadModule: "glx"
[  2732.536] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  2732.544] (II) Module glx: vendor="X.Org Foundation"
[  2732.545]    compiled for 1.19.2, module version = 1.0.0
[  2732.545]    ABI class: X.Org Server Extension, version 10.0
[  2732.545] (II) LoadModule: "fbturbo"
[  2732.546] (WW) Warning, couldn't open module fbturbo
[  2732.546] (II) UnloadModule: "fbturbo"
[  2732.546] (II) Unloading fbturbo
[  2732.546] (EE) Failed to load module "fbturbo" (module does not exist, 0)
[  2732.546] (II) LoadModule: "fbdev"
[  2732.546] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[  2732.547] (II) Module fbdev: vendor="X.Org Foundation"
[  2732.547]    compiled for 1.19.0, module version = 0.4.4
[  2732.547]    Module class: X.Org Video Driver
[  2732.547]    ABI class: X.Org Video Driver, version 23.0
[  2732.547] (II) FBDEV: driver for framebuffer: fbdev
[  2732.554] (WW) Falling back to old probe method for fbdev
[  2732.554] (II) Loading sub module "fbdevhw"
[  2732.554] (II) LoadModule: "fbdevhw"
[  2732.554] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[  2732.555] (II) Module fbdevhw: vendor="X.Org Foundation"
[  2732.555]    compiled for 1.19.2, module version = 0.0.2
[  2732.555]    ABI class: X.Org Video Driver, version 23.0
[  2732.555] (II) FBDEV(0): using /dev/fb1
[  2732.556] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[  2732.556] (EE) Screen 0 deleted because of no matching config section.
[  2732.556] (II) UnloadModule: "fbdev"
[  2732.556] (II) UnloadSubModule: "fbdevhw"
[  2732.556] (EE) Device(s) detected, but none match those in the config file.
[  2732.556] (EE)
Fatal server error:
[  2732.556] (EE) no screens found(EE)
[  2732.556] (EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[  2732.556] (EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
[  2732.556] (EE)
[  2732.565] (EE) Server terminated with error (1). Closing log file.

**Comment by nato2k** [comment]
Have you installed the TFT drivers?

`cd ~
wget https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/adafruit-pitft.sh
chmod +x adafruit-pitft.sh
sudo ./adafruit-pitft.sh`

Choose 4 for the 3.5" screen and 1 for 90 degrees, then make sure to answer No to the first question regarding the console and then Yes to HDMI.

**Comment by serv16** [comment]
No, I did not install this driver, I just followed what you told me but now I have a blank screen.

**Comment by nato2k** [comment]
reboot your Pi and see what happens.  You may need to reinstall Octoprint-TFT.

**Comment by serv16** [comment]
I reboot the pi and reinstall OCTOPRINT-TFT, but still white screen.

**Comment by nato2k** [comment]
Can you try `systemctl status display-manager` again?

**Comment by serv16** [comment]
I executed `systemctl status display-manager`, below the result :

> ● octoprint-tft.service - OctoPrint-TFT
   Loaded: loaded (/lib/systemd/system/octoprint-tft.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-02-15 18:16:03 UTC; 8s ago
 Main PID: 985 (xinit)
      CPU: 75ms
   CGroup: /system.slice/octoprint-tft.service
           └─985 /usr/bin/xinit /usr/bin/OctoPrint-TFT -- :0 -nolisten tcp -nocursor
Feb 15 18:16:03 octopi xinit[985]: (EE)
Feb 15 18:16:03 octopi xinit[985]: Fatal server error:
Feb 15 18:16:03 octopi xinit[985]: (EE) no screens found(EE)
Feb 15 18:16:03 octopi xinit[985]: (EE)
Feb 15 18:16:03 octopi xinit[985]: Please consult the The X.Org Foundation support
Feb 15 18:16:03 octopi xinit[985]:          at http://wiki.x.org
Feb 15 18:16:03 octopi xinit[985]:  for help.
Feb 15 18:16:03 octopi xinit[985]: (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
Feb 15 18:16:03 octopi xinit[985]: (EE)
Feb 15 18:16:03 octopi xinit[985]: (EE) Server terminated with error (1). Closing log file.

**Comment by nato2k** [comment]
Seems like the TFT install didn't work.  All I can think of is to run it again.  Otherwise head over to Adafruit and see if they can help.

**Comment by serv16** [comment]
Again thank you, but originally this TFT is not an Adafruit.
it's a chinese screen coming from Aliexpress [https://www.aliexpress.com/item/Raspberry-Pi-3-Model-B-Plus-3-5-inch-TFT-Touch-Screen-LCD-Display-with-New/32906504749.html?spm=a2g0s.12269583.0.0.37ff7d250sCxBY](https://www.aliexpress.com/item/Raspberry-Pi-3-Model-B-Plus-3-5-inch-TFT-Touch-Screen-LCD-Display-with-New/32906504749.html?spm=a2g0s.12269583.0.0.37ff7d250sCxBY) with this driver there : [https://github.com/goodtft/LCD-show](https://github.com/goodtft/LCD-show).

**Comment by nato2k** [comment]
Oh, sorry about that!  Follow the driver instructions on the link you sent me, that should fix it.

**Comment by serv16** [comment]
Unfortunately with the original driver, I arrive at the octopi login page as at the beginning and no Octoprint-TFT page.

**Comment by nato2k** [comment]
Try sudo octoprint-tft and see if it loads.

I am only familiar with the adafruit drivers, which ask if you want to mirror HDMI or if you want command line, I thought maybe that is the problem but reviewing the scripts seems to indicate that it does that automatically.

**Comment by serv16** [comment]
By executing the command `sudo OctoPrint-TFT` :

> INFO[0000] Found API key at "/home/pi/.octoprint/config.yaml" file  file=main.go                                       func=main.init.0 line=50
Unable to init server: Could not connect: Connection refused

**Comment by nato2k** [comment]
Try adding your API key to the config file.

Is your RPI connected to the USB port on the printer?

**Comment by serv16** [comment]
Yes, the printer is connected.
I noticed that my TFT was very similar to [Waveshare TFT (model A).](https://www.waveshare.com/product/3.5inch-RPi-LCD-A.htm).
So I tried by installing the Waveshare driver, the screen turns on.
After I followed the [TFT Installation Tips wiki](https://github.com/CJeffyB/OctoPrint-TFT/wiki/TFT-Installation-Tips) and got a black screen with the dash.
![img_20190217_084520](https://user-images.githubusercontent.com/32510358/52910429-9e5f3180-3297-11e9-8177-0edcc939cdfb.jpg)

While searching on the net, I modified Option "fbdev" "/dev/fb1" in "fbdev" "/dev/fb0" in the 99-pitft.conf file as explained on this site [http://www.plastibots.com/index.php/2018/06/02/adding-tft-lcd-to-raspberry-pi-octopi-rig-touchui/](http://www.plastibots.com/index.php/2018/06/02/adding-tft-lcd-to-raspberry-pi-octopi-rig-touchui/) and miracle octoprint-TFT launches on my screen.
![img_20190217_092559](https://user-images.githubusercontent.com/32510358/52910435-a7500300-3297-11e9-9124-e29d5a3cdc5e.jpg)

**Comment by nad22** [comment]
if you have problems with calibration just follow this 2 links:
a) calibration transorm matrix: https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Troubleshooting#calibration

b) use edev driver: 
https://www.max2play.com/en/forums/topic/support-for-sharewave-3-5-lcd-touchscreen/
