### ISSUE TITLE
Cant get UI to work with Kuman 3.5 tft using goodtft driver.

### ISSUE THREAD

**Issue by littleferris** [mcuadros/OctoPrint-TFT#59]
![tft](https://user-images.githubusercontent.com/21049780/54451428-7341f380-4718-11e9-803c-69e7dfcd2e84.jpg)
So I have tried getting this to work a bunch of times but after I have gone through everything I only ever get a terminal with octopi login: on my tft. I have tried installing the tft driver first, and then last.  

My order of installing stuff has been.
1. Flash Octopi onto sd.
2. Install all dependencies
3. Follow Octoprint recommended installation section
4. Install tft drivers from the goodtft/lcd-show github.(Have tried this being in the number 2 spot also).

Is there anything I am missing? Or is there a different order I should be trying?

![tft](https://user-images.githubusercontent.com/21049780/54451428-7341f380-4718-11e9-803c-69e7dfcd2e84.jpg)

**Comment by pkret** [comment]
I usually follow this guide https://pastebin.com/rsMa5K1v and skip the chromium and touchui bits and instead of lines 99-104, i will do octoprint-tft install, as stated in the readme (actually I build it from scratch with a couple of patches, but this makes no difference here). I guess, line 95 fixes your issue.

**Comment by littleferris** [comment]
So @pkret just to make sure I do this right. 

Flash octoprint

follow lines 49-95

install dependencies

run these two lines
1. wget https://github.com/mcuadros/OctoPrint-TFT/releases/download/v0.1.0/octoprint-tft_0.1.0-1.jessie_armhf.deb

2. dpkg -i octoprint-tft_0.1.0-1.jessie_armhf.deb

and then it should be working? Or atleast showing up on my screen.

**Comment by pkret** [comment]
Depending on the orientation of your screen, you may have to do lines 110-131 as well, then do this:
sudo apt-get install libgtk-3-0 xserver-xorg xinit
wget https://github.com/mcuadros/OctoPrint-TFT/releases/download/v0.1.2/octoprint-tft_0.1.2-1.jessie_armhf.deb
sudo dpkg -i octoprint-tft_0.1.2-1.jessie_armhf.deb

...as stated on the release page https://github.com/mcuadros/OctoPrint-TFT/releases

**Comment by littleferris** [comment]
Thanks. I will give that a shot and see if it works.

**Comment by littleferris** [comment]
Worked great! Thanks my guy!
