### ISSUE TITLE
Anyone have an idea on how to get this working with an HDMI Screen?

### ISSUE THREAD

**Issue by littleferris** [mcuadros/OctoPrint-TFT#60]
This is all I can get. Seems the resolution is way off. Using the newest release

Edit: I have resolution set properly in the config.txt and the octoprint-tft config too. 

![image](https://user-images.githubusercontent.com/21049780/54481931-0f472a00-4801-11e9-9e95-d9534342a950.png)

**Comment by nachosan100** [comment]
same here....saw this on fb and it looks a lot more interesting than TouchUI. Just how to get it to go past the octopi logo?

**Comment by Houdini7** [comment]
Is it connected to your printer, and is the printer on?

**Comment by nachosan100** [comment]
> Is it connected to your printer, and is the printer on?

got it. after the printer was on AND connected, it took a minute or two and the icons showed up. Now i "only" have to solve, that i am using 1/8 of the 7inch screen and everything is tiny....so off to tackling the next item. Thanks for point this out!

**Comment by littleferris** [comment]
@Houdini7 my issue isn’t the octopus. But it should be centered. For me the issue is resolution. I know the octopus is there till connection is made.

**Comment by littleferris** [comment]
I used a different branch and the issue I had was fixed.
