### ISSUE TITLE
Unable to connect to “http://localhost” (Key:true), maybe OctoPrint not running?

### ISSUE THREAD

**Issue by NelsonPJ** [mcuadros/OctoPrint-TFT#7]
I've got a current installation of OctoPrint with TouchUI on an RPi3 with an Adafruit TFT.  I installed v0.1.2 of OctoPrint-TFT for Jesse following the instructions here, and then removed the autostart TouchUI files.

Now when my RPi boots I get the picture of an octopus from OctoPrint-TFT (so it's launching) but after a few seconds it shows this error message:

	Unable to connect to “http://localhost” (Key:true),
	maybe OctoPrint not running?

My OctoPrint server is running - I can access if from a webbrowser on my network - how do I debug this?

I tried editing /etc/octoprint-tft-environment and added my API key and the location of my config.yaml (which is in the default location of /home/pi/.octoprint/config.yaml) but that didn't help.

**Comment by mcuadros** [comment]
Can you execute `wget http://localhost` from a shell in the RPi?

**Comment by NelsonPJ** [comment]
Thanks for the pointer - I couldn't figure out how to start debugging this issue (I'm not that familiar with this side of RPi/Linux).  I can't connect to http://localhost

```
pi@octopi:~ $ wget http://localhost
--2018-01-13 09:09:16--  http://localhost/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:80... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.
```

I googled this issue, and one suggestion was to run "netstat -lptn".  From the results I think I should be pointing to port 5000?

```
pi@octopi:~ $ netstat -lptn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      586/python      
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::8080                 :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               

```

So I put this in my octoprint-tft-environment file - and it works!

```
# OctoPrint HTTP address, default http://localhost
OCTOPRINT_HOST=http://localhost:5000

```

The interface looks great - so much easier to control than TouchUI.  Will try a few prints today to see how it goes...

**Comment by mcuadros** [comment]
Nice, what I going to do, is try to read also the port from the config file. To avoid this kind of problems to other people. Thanks for using it.
